# =============================================================================
# Caddy - Reverse Proxy
# =============================================================================
# Caddy sits in front of all your services and routes traffic to the right
# container based on the URL. It also handles HTTPS certificates automatically
# when you add a domain later.
#
# Right now (no domain), Caddy listens on multiple ports and forwards each
# to the appropriate service. See caddy/Caddyfile for the routing rules.
# =============================================================================

services:
  caddy:
    image: caddy:2.9.1
    container_name: caddy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    ports:
      # --- Phase 1 ---
      - "${SERVER_IP:?Set SERVER_IP in .env}:80:80"           # Homepage dashboard (landing page)
      - "${SERVER_IP:?Set SERVER_IP in .env}:8090:8090"       # Uptime Kuma
      - "${SERVER_IP:?Set SERVER_IP in .env}:8091:8091"       # AdGuard Home UI
      # --- Phase 2 ---
      # Vaultwarden serves its own HTTPS (ROCKET_TLS) — not proxied through Caddy
      - "${SERVER_IP:?Set SERVER_IP in .env}:8093:8093"       # Jellyfin (media server)
      - "${SERVER_IP:?Set SERVER_IP in .env}:8094:8094"       # Sonarr (TV management)
      - "${SERVER_IP:?Set SERVER_IP in .env}:8095:8095"       # Radarr (movie management)
      - "${SERVER_IP:?Set SERVER_IP in .env}:8096:8096"       # Prowlarr (indexer manager)
      - "${SERVER_IP:?Set SERVER_IP in .env}:8097:8097"       # qBittorrent (download client)
      - "${SERVER_IP:?Set SERVER_IP in .env}:8098:8098"       # Home Assistant (smart home)
      - "${SERVER_IP:?Set SERVER_IP in .env}:8099:8099"       # Syncthing (file sync)
      # - "${SERVER_IP:?Set SERVER_IP in .env}:443:443"       # HTTPS — uncomment when you add a domain
    volumes:
      # Path is relative to THIS file (stacks/), so ../caddy/ = repo root caddy/
      - ../caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      # Caddy stores TLS certificates and state here
      - caddy_data:/data
      - caddy_config:/config
    # Uncomment when switching to domain mode (see docs/adding-a-domain.md):
    # environment:
    #   - DOMAIN=${DOMAIN}
    #   - ACME_EMAIL=${ACME_EMAIL}
    networks:
      - proxy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config

# Network is created by the root compose.yaml via the include directive.
# These stack files must be run via the root compose.yaml, not independently.
networks:
  proxy:
    external: true
