# =============================================================================
# Caddy - Reverse Proxy
# =============================================================================
# Caddy sits in front of all your services and routes traffic to the right
# container based on the URL. It also handles HTTPS certificates automatically
# when you add a domain later.
#
# Right now (no domain), Caddy listens on multiple ports and forwards each
# to the appropriate service. See caddy/Caddyfile for the routing rules.
# =============================================================================

services:
  caddy:
    image: caddy:2.9.1
    container_name: caddy
    restart: unless-stopped
    ports:
      # --- Phase 1 ---
      - "80:80"           # Homepage dashboard (landing page)
      - "8090:8090"       # Uptime Kuma
      - "8091:8091"       # AdGuard Home UI
      # --- Phase 2 ---
      - "8092:8092"       # Vaultwarden (password manager)
      - "8093:8093"       # Jellyfin (media server)
      - "8094:8094"       # Sonarr (TV management)
      - "8095:8095"       # Radarr (movie management)
      - "8096:8096"       # Prowlarr (indexer manager)
      - "8097:8097"       # qBittorrent (download client)
      - "8098:8098"       # Home Assistant (smart home)
      - "8099:8099"       # Syncthing (file sync)
      # - "443:443"       # HTTPS — uncomment when you add a domain
    volumes:
      # Path is relative to THIS file (stacks/), so ../caddy/ = repo root caddy/
      - ../caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      # Caddy stores TLS certificates and state here
      - caddy_data:/data
      - caddy_config:/config
    environment:
      # Server IP for Vaultwarden HTTPS (tls internal needs a hostname, not a bare port)
      - SERVER_IP=${SERVER_IP:-localhost}
      # Uncomment when switching to domain mode (see docs/adding-a-domain.md):
      # - DOMAIN=${DOMAIN}
      # - ACME_EMAIL=${ACME_EMAIL}
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "caddy", "version"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config

# Network is created by the root compose.yaml via the include directive.
# These stack files must be run via the root compose.yaml, not independently.
networks:
  proxy:
    external: true
