# =============================================================================
# cAdvisor - Container Metrics
# =============================================================================
# Exports per-container resource usage metrics (CPU, memory, network, I/O).
# Prometheus scrapes these at :8080/metrics.
#
# SECURITY NOTES:
# - Requires SYS_ADMIN capability for cgroup access (cannot avoid this)
# - All host mounts are READ-ONLY except /var/run (needed for Docker socket)
# - Not user-facing — data is consumed by Prometheus → Grafana
#
# DOCKER 29+ / CONTAINERD IMAGE STORE: Requires cAdvisor v0.54.0+ which
# auto-detects the containerd-snapshotter layout. The image registry moved
# from gcr.io to ghcr.io starting at v0.53.0.
#
# GRAFANA DASHBOARD: Import "Docker Container & Host Metrics" (ID 14282)
# =============================================================================

services:
  cadvisor:
    image: ghcr.io/google/cadvisor:0.56.2
    container_name: cadvisor
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SYS_ADMIN
      - DAC_READ_SEARCH
    command:
      # Disable per-container disk metrics — the overlayfs layer traversal
      # takes 1-2 min per container on Docker 29, blocking /metrics and causing
      # Prometheus scrape timeouts. Host disk is covered by Node Exporter.
      - --disable_metrics=disk,diskIO,hugetlb,referenced_memory
      # Only monitor Docker containers (skip system-level cgroups)
      - --docker_only=true
      # Collect stats every 10s instead of default 1s — Prometheus scrapes
      # every 30s, so 1s resolution is wasteful and burns CPU.
      - --housekeeping_interval=10s
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - proxy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8080/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      start_period: 15s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256m

networks:
  proxy:
    external: true
