# =============================================================================
# Calibre-Web - Ebook Server
# =============================================================================
# Calibre-Web provides a web interface for browsing, reading, and downloading
# ebooks. It uses a Calibre library database (metadata.db) to organize books.
#
# FIRST RUN:
#   1. Open http://SERVER_IP:8102
#   2. Log in with default credentials: admin / admin123
#   3. IMMEDIATELY change the admin password (Admin > Edit User)
#   4. Set the Calibre library location: /books
#      - If you already have a Calibre library, copy it to /srv/media/books
#      - If not, Calibre-Web needs a metadata.db file in /books
#        Create one with Calibre desktop, or use an empty Calibre library
#   5. Optionally enable public registration or create user accounts
#
# BOOKS: Place ebook files in /srv/media/books on the host.
# This directory is shared with Kavita (which mounts it read-only).
#
# Access at: http://SERVER_IP:8102 (routed through Caddy)
# =============================================================================

services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:0.6.24
    container_name: calibre-web
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETUID
      - SETGID
    environment:
      - TZ=${TZ:-UTC}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - calibreweb_config:/config
      - ${MEDIA_PATH:-/srv/media}/books:/books
    networks:
      - proxy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8083 || exit 1"]
      interval: 30s
      timeout: 5s
      start_period: 15s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256m

volumes:
  calibreweb_config:
    name: calibreweb_config

networks:
  proxy:
    external: true
