# =============================================================================
# Docker Socket Proxy - Secure Docker API Access
# =============================================================================
# The Docker socket (/var/run/docker.sock) grants root-equivalent access to
# the host. Instead of mounting it directly into Homepage, we proxy it through
# this container which only exposes safe, read-only API endpoints.
#
# Homepage connects to this proxy (port 2375) instead of the raw socket.
# The proxy blocks dangerous endpoints (exec, create, push, etc.) while
# allowing Homepage to read container status and stats.
#
# See: https://github.com/Tecnativa/docker-socket-proxy
# =============================================================================

services:
  dockerproxy:
    image: tecnativa/docker-socket-proxy:v0.4.2
    container_name: dockerproxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      # Read-only access to containers and images (needed by Homepage)
      - CONTAINERS=1
      - IMAGES=1
      # Block all write/dangerous operations
      - POST=0
      - AUTH=0
      - SECRETS=0
      - NETWORKS=0
      - VOLUMES=0
      - SERVICES=0
      - TASKS=0
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - DISTRIBUTION=0
      - EXEC=0
      - GRPC=0
      - NODES=0
      - PLUGINS=0
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:2375/version || exit 1"]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 64m

networks:
  proxy:
    external: true
