# =============================================================================
# Homepage - Dashboard
# =============================================================================
# A clean, fast dashboard that shows all your services at a glance.
# Configuration lives in homepage/config/ (version-controlled YAML files).
#
# Homepage connects to the Docker socket proxy (dockerproxy container)
# instead of the raw Docker socket — this limits API access to safe,
# read-only endpoints (container list/inspect only).
#
# Access at: http://SERVER_IP (the default landing page via Caddy)
# =============================================================================

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.10.9
    container_name: homepage
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
      - /run
    environment:
      # Which hostnames/IPs are allowed to access the dashboard.
      # Without this, Homepage rejects requests as a security measure.
      # Uses wildcard by default since this is behind a LAN/Tailscale.
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS:-*}
      # Passed to config files as {{HOMEPAGE_VAR_SERVER_IP}}
      - HOMEPAGE_VAR_SERVER_IP=${SERVER_IP:-localhost}
      # AdGuard credentials for widget (set after completing AdGuard wizard)
      - HOMEPAGE_VAR_ADGUARD_USER=${ADGUARD_USER:-}
      - HOMEPAGE_VAR_ADGUARD_PASS=${ADGUARD_PASS:-}
      # Phase 2 widget API keys (set after first launch of each service)
      - HOMEPAGE_VAR_JELLYFIN_API_KEY=${JELLYFIN_API_KEY:-}
      - HOMEPAGE_VAR_SONARR_API_KEY=${SONARR_API_KEY:-}
      - HOMEPAGE_VAR_RADARR_API_KEY=${RADARR_API_KEY:-}
      - HOMEPAGE_VAR_PROWLARR_API_KEY=${PROWLARR_API_KEY:-}
      - HOMEPAGE_VAR_QBITTORRENT_USER=${QBITTORRENT_USER:-admin}
      - HOMEPAGE_VAR_QBITTORRENT_PASS=${QBITTORRENT_PASS:-}
      - HOMEPAGE_VAR_HOMEASSISTANT_API_KEY=${HOMEASSISTANT_API_KEY:-}
      # Phase 3 widget credentials
      - HOMEPAGE_VAR_KAVITA_USER=${KAVITA_USER:-}
      - HOMEPAGE_VAR_KAVITA_PASS=${KAVITA_PASS:-}
      - TZ=${TZ:-UTC}
    depends_on:
      dockerproxy:
        condition: service_healthy
    volumes:
      # Dashboard config files (we version-control these in the repo)
      - ../homepage/config:/app/config
    networks:
      - proxy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 5s
      start_period: 15s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256m

networks:
  proxy:
    external: true
