# =============================================================================
# Jellyfin - Media Server
# =============================================================================
# Jellyfin streams your movies, TV shows, and music to any device. It's a
# free, open-source alternative to Plex with no account or subscription needed.
#
# SETUP:
#   1. Open http://SERVER_IP:8093 to run the setup wizard
#   2. Create an admin account
#   3. Add media libraries:
#      - Movies → /media/movies
#      - TV Shows → /media/tv
#   4. Install Jellyfin apps on your devices (phone, TV, etc.)
#   5. Add your API key to .env (JELLYFIN_API_KEY) for the Homepage widget
#      Generate in: Dashboard > API Keys > Add
#
# HARDWARE TRANSCODING (AMD VAAPI):
#   The HP desktop has an AMD Radeon Vega 11 iGPU for hardware-accelerated
#   video transcoding. The /dev/dri device is passed through below.
#
#   SERVER SETUP (one-time):
#   1. Verify /dev/dri exists: ls -la /dev/dri/
#   2. Add your user to the render/video groups:
#      sudo usermod -aG render,video $USER
#   3. Log out and back in (or reboot)
#
#   JELLYFIN SETUP:
#   1. Dashboard > Playback > Transcoding > Hardware acceleration
#      → Select "Video Acceleration API (VAAPI)"
#      → Device: /dev/dri/renderD128
#   2. Enable hardware decoding for: H264, HEVC, VP9, AV1 (if supported)
#
# Access at: http://SERVER_IP:8093 (routed through Caddy)
# =============================================================================

services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.6
    container_name: jellyfin
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      - TZ=${TZ:-UTC}
      # Tells clients the server's address for direct connections
      - JELLYFIN_PublishedServerUrl=${SERVER_IP:-localhost}
    volumes:
      # Server config, metadata cache, database
      - jellyfin_config:/config
      # Media library — read-only because Jellyfin only reads, never writes media
      - ${MEDIA_PATH:-/srv/media}:/media:ro
    networks:
      - proxy
    devices:
      - /dev/dri:/dev/dri
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8096/health || exit 1"]
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "2.00"
          memory: 1024m

volumes:
  jellyfin_config:
    name: jellyfin_config

networks:
  proxy:
    external: true
