# =============================================================================
# qBittorrent - Download Client (routed through Gluetun VPN)
# =============================================================================
# qBittorrent handles downloads for Sonarr and Radarr. All torrent traffic
# is routed through Gluetun's VPN tunnel — your home IP is never exposed
# to torrent peers.
#
# FIRST RUN:
#   1. The default username is 'admin'
#   2. A RANDOM password is generated on first launch. Find it with:
#      docker compose logs qbittorrent | grep "temporary password"
#   3. Log in at http://SERVER_IP:8097 and change the password immediately
#      (Tools > Options > Web UI > Authentication)
#   4. Add your credentials to .env (QBITTORRENT_USER / QBITTORRENT_PASS)
#      for the Homepage dashboard widget
#
# DOWNLOAD PATHS (important for hardlinks):
#   Configure these in the qBittorrent web UI (Tools > Options > Downloads):
#   - Default save path: /media/downloads/complete
#   - Keep incomplete torrents in: /media/downloads/incomplete
#   Then set up categories (right-click in sidebar > New Category):
#   - Category "movies" → save path: /media/downloads/complete/movies
#   - Category "tv"     → save path: /media/downloads/complete/tv
#
# NETWORKING:
#   qBittorrent uses network_mode: "service:gluetun", which means it shares
#   Gluetun's network stack entirely. It has NO network of its own — Caddy
#   and Homepage reach it via "gluetun:8080" (Gluetun's container name).
#
# Access at: http://SERVER_IP:8097 (routed through Caddy)
# =============================================================================

services:
  qbittorrent:
    image: linuxserver/qbittorrent:5.1.4
    container_name: qbittorrent
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
      - SETUID
      - SETGID
    # Route ALL network traffic through Gluetun's VPN tunnel.
    # This replaces the 'networks' and 'ports' sections — qBittorrent
    # shares Gluetun's network namespace and uses its IP.
    network_mode: "service:gluetun"
    depends_on:
      gluetun:
        condition: service_healthy
    environment:
      - TZ=${TZ:-UTC}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - WEBUI_PORT=8080
    volumes:
      # App config, torrent state, resume data
      - qbittorrent_config:/config
      # Media root — must match the same mount in Sonarr/Radarr for hardlinks
      - ${MEDIA_PATH:-/srv/media}:/media
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/api/v2/app/version || exit 1"]
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 256m

volumes:
  qbittorrent_config:
    name: qbittorrent_config
