# =============================================================================
# Vaultwarden - Password Manager
# =============================================================================
# A lightweight, self-hosted Bitwarden-compatible password manager written in
# Rust. Works with all official Bitwarden apps and browser extensions.
#
# SETUP:
#   1. Open http://SERVER_IP:8092 and create your account
#   2. IMPORTANT: After creating your account, set VAULTWARDEN_SIGNUPS_ALLOWED=false
#      in .env and run: docker compose up -d vaultwarden
#      This prevents anyone else from creating accounts on your server.
#
# HTTPS NOTE:
#   Caddy serves this with a self-signed certificate (tls internal) because the
#   Vaultwarden web vault requires HTTPS for the browser's Web Crypto API.
#   Your browser will show a one-time certificate warning — accept it.
#   For mobile apps, consider Tailscale MagicDNS HTTPS or a real domain.
#
# Access at: https://SERVER_IP:8092 (HTTPS via Caddy self-signed cert)
# =============================================================================

services:
  vaultwarden:
    image: vaultwarden/server:1.35.4
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
      # Allow new account registrations. Set to 'false' after creating your account!
      - SIGNUPS_ALLOWED=${VAULTWARDEN_SIGNUPS_ALLOWED:-true}
    volumes:
      # All vault data: encrypted passwords, attachments, config, SQLite database
      - vaultwarden_data:/data
    networks:
      - proxy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:80/alive || exit 1"]
      interval: 30s
      timeout: 5s
      start_period: 15s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 128m

volumes:
  vaultwarden_data:
    name: vaultwarden_data

networks:
  proxy:
    external: true
