# Top-bar widgets (above service cards)
# Docs: https://gethomepage.dev/configs/widgets/

- resources:
    label: System
    cpu: true
    memory: true
    disk: /
    refresh: 5000

- resources:
    label: Media
    disk: /media
    refresh: 30000

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short
      hour12: true

- search:
    provider: google
    target: _blank
    focus: false
    showSearchSuggestions: true
