# Top-bar widgets (above service cards)
# Docs: https://gethomepage.dev/configs/widgets/

- datetime:
    text_size: 2xl
    format:
      dateStyle: full
      timeStyle: short
      hour12: true

- search:
    provider: google
    target: _blank
    focus: false
    showSearchSuggestions: true
